"""
Clinical workflow specifications for SevaCare V2.

This file is intentionally a configuration/design layer. It does not add new
agents, RAG, or controller behavior by itself. Future controller code can use
these workflow definitions to select the next missing clinical field before
calling a natural-language phrasing layer.

Evidence source:
    FOLLOWUPQ_ANALYSIS.md, derived from data/followupq.csv.
"""

from __future__ import annotations


CLINICAL_WORKFLOWS = {
    "fever": {
        "display_name": "Fever",
        "evidence": {
            "matching_cases": 5,
            "total_questions": 57,
            "strongest_groups": [
                "associated_systemic",
                "associated_respiratory",
                "severity_intensity",
                "medication_response",
                "cardiac_red_flags",
                "duration_onset",
            ],
        },
        "required_fields": [
            "duration",
            "temperature_max",
            "associated_respiratory_symptoms",
            "associated_systemic_symptoms",
            "medication_taken",
            "medication_response",
            "hydration_status",
            "vomiting_diarrhea",
            "danger_red_flags",
            "exposure_infection",
        ],
        "priority_order": [
            "duration",
            "temperature_max",
            "danger_red_flags",
            "associated_respiratory_symptoms",
            "associated_systemic_symptoms",
            "medication_taken",
            "medication_response",
            "hydration_status",
            "vomiting_diarrhea",
            "exposure_infection",
        ],
        "field_dependencies": {
            "medication_response": ["medication_taken"],
            "medication_name": ["medication_taken"],
        },
        "conditional_priority": [
            {
                "when": {"temperature_max_gte": 103},
                "promote": [
                    "danger_red_flags",
                    "medication_response",
                    "hydration_status",
                    "vomiting_diarrhea",
                ],
            },
            {
                "when": {"temperature_max_gte": 105},
                "promote": [
                    "danger_red_flags",
                    "medication_response",
                ],
                "triage_hint": "High fever; ask concrete safety screen.",
            },
        ],
        "red_flags": [
            "shortness_of_breath",
            "confusion",
            "stiff_neck",
            "severe_weakness",
            "persistent_vomiting",
            "chest_pain",
            "fainting",
            "rash",
            "dehydration",
        ],
        "field_questions": {
            "duration": "How long have you had the fever?",
            "temperature_max": "What has been the highest temperature you measured, and how did you measure it?",
            "associated_respiratory_symptoms": "Are you also having cough, sore throat, congestion, wheezing, or trouble breathing?",
            "associated_systemic_symptoms": "Are you having chills, sweating, body aches, or severe weakness with the fever?",
            "medication_taken": "Have you taken any fever medicine such as paracetamol, acetaminophen, or ibuprofen?",
            "medication_response": "After taking the medicine, did the fever come down, and what is your temperature now?",
            "hydration_status": "Are you able to drink fluids and urinate normally?",
            "vomiting_diarrhea": "Have you had vomiting or diarrhea since the fever started?",
            "danger_red_flags": "With this fever, are you having trouble breathing, confusion, stiff neck, severe weakness, persistent vomiting, chest pain, fainting, rash, or signs of dehydration?",
            "exposure_infection": "Has anyone around you been sick, or have you had recent COVID, flu, travel, or mosquito exposure?",
        },
        "nlice_fields_to_keep": [
            "nature",
            "chronology",
        ],
        "structured_fields": [
            "temperature_max",
            "temperature_current",
            "medication_taken",
            "medication_response",
            "hydration_status",
            "urination_normal",
            "cough",
            "shortness_of_breath",
            "vomiting",
            "diarrhea",
            "chills",
            "weakness",
            "rash",
            "sick_contacts",
            "travel_or_mosquito_exposure",
        ],
    },
    "cough": {
        "display_name": "Cough",
        "evidence": {
            "matching_cases": 9,
            "total_questions": 95,
            "strongest_groups": [
                "associated_respiratory",
                "associated_systemic",
                "exposure_infection",
                "trigger_pattern",
                "duration_onset",
                "medication_response",
                "cardiac_red_flags",
            ],
        },
        "required_fields": [
            "duration",
            "cough_character",
            "sputum",
            "shortness_of_breath",
            "wheezing",
            "fever_chills_body_aches",
            "nasal_throat_symptoms",
            "medication_or_inhaler_response",
            "exposure_infection",
            "chest_pain_palpitations",
        ],
        "priority_order": [
            "duration",
            "shortness_of_breath",
            "wheezing",
            "cough_character",
            "sputum",
            "fever_chills_body_aches",
            "chest_pain_palpitations",
            "nasal_throat_symptoms",
            "medication_or_inhaler_response",
            "exposure_infection",
            "reflux_or_eating_trigger",
        ],
        "conditional_priority": [
            {
                "when": {"shortness_of_breath": True},
                "promote": [
                    "danger_red_flags",
                    "chest_pain_palpitations",
                ],
            },
            {
                "when": {"wheezing": True},
                "promote": [
                    "medication_or_inhaler_response",
                ],
            },
        ],
        "red_flags": [
            "shortness_of_breath_at_rest",
            "chest_pain",
            "blue_lips",
            "confusion",
            "hemoptysis",
            "inability_to_speak_full_sentences",
        ],
        "field_questions": {
            "duration": "How long have you had the cough?",
            "shortness_of_breath": "Are you short of breath or having trouble catching your breath?",
            "wheezing": "Have you noticed wheezing?",
            "cough_character": "Is the cough dry, or are you bringing up mucus or phlegm?",
            "sputum": "If you are coughing up mucus, what color is it?",
            "fever_chills_body_aches": "Have you had fever, chills, or body aches with the cough?",
            "nasal_throat_symptoms": "Do you also have sore throat, runny nose, congestion, or post-nasal drip?",
            "medication_or_inhaler_response": "Have you used any cough medicine or an inhaler, and did it help?",
            "exposure_infection": "Have you been around anyone sick, or tested for COVID or flu?",
            "chest_pain_palpitations": "Are you having chest pain, chest tightness, or palpitations?",
            "reflux_or_eating_trigger": "Does the cough get worse after eating or when lying down?",
            "danger_red_flags": "Are you struggling to breathe, unable to speak full sentences, confused, coughing blood, or having chest pain?",
        },
        "nlice_fields_to_keep": [
            "nature",
            "chronology",
            "excitation",
        ],
        "structured_fields": [
            "cough_productive",
            "sputum_color",
            "shortness_of_breath",
            "wheezing",
            "fever",
            "chills",
            "sore_throat",
            "nasal_congestion",
            "chest_pain",
            "inhaler_use",
            "inhaler_response",
            "sick_contacts",
            "reflux_or_eating_trigger",
        ],
    },
    "headache": {
        "display_name": "Headache",
        "evidence": {
            "matching_cases": 6,
            "total_questions": 47,
            "strongest_groups": [
                "associated_respiratory",
                "associated_systemic",
                "exposure_infection",
                "duration_onset",
                "medication_response",
                "severity_intensity",
                "neuro_red_flags",
            ],
        },
        "required_fields": [
            "duration",
            "severity",
            "sudden_or_worst_headache",
            "vision_neurologic_symptoms",
            "fever_stiff_neck",
            "sinus_respiratory_symptoms",
            "medication_response",
            "hydration_sleep_meals",
            "exposure_recent_illness",
        ],
        "priority_order": [
            "sudden_or_worst_headache",
            "vision_neurologic_symptoms",
            "fever_stiff_neck",
            "duration",
            "severity",
            "sinus_respiratory_symptoms",
            "medication_response",
            "hydration_sleep_meals",
            "exposure_recent_illness",
            "progression_pattern",
        ],
        "conditional_priority": [
            {
                "when": {"sudden_or_worst_headache": True},
                "promote": [
                    "danger_red_flags",
                ],
            },
            {
                "when": {"fever": True},
                "promote": [
                    "fever_stiff_neck",
                    "vision_neurologic_symptoms",
                ],
            },
        ],
        "red_flags": [
            "sudden_onset",
            "worst_headache",
            "vision_changes",
            "confusion",
            "fainting",
            "weakness_one_side",
            "stiff_neck",
            "fever",
            "recent_head_injury",
        ],
        "field_questions": {
            "duration": "How long have you had the headache?",
            "severity": "On a scale from 0 to 10, how bad is the headache at its worst?",
            "sudden_or_worst_headache": "Did the headache start suddenly, or is it the worst headache you have had?",
            "vision_neurologic_symptoms": "Are you having vision changes, confusion, fainting, dizziness, or weakness on one side?",
            "fever_stiff_neck": "Do you have fever or neck stiffness with the headache?",
            "sinus_respiratory_symptoms": "Do you also have sinus pressure, nasal drainage, cough, sore throat, or shortness of breath?",
            "medication_response": "Have you taken anything for the headache, and did it help?",
            "hydration_sleep_meals": "Have you been drinking fluids, sleeping normally, and eating as usual?",
            "exposure_recent_illness": "Were you recently sick, or have you tested for COVID or flu?",
            "progression_pattern": "Is the headache getting better, worse, or staying about the same?",
            "danger_red_flags": "Are you having sudden worst headache, vision changes, confusion, fainting, one-sided weakness, stiff neck, fever, or recent head injury?",
        },
        "nlice_fields_to_keep": [
            "nature",
            "location",
            "intensity",
            "chronology",
            "excitation",
        ],
        "structured_fields": [
            "sudden_onset",
            "worst_headache",
            "vision_changes",
            "confusion",
            "fainting",
            "weakness_one_side",
            "stiff_neck",
            "fever",
            "nasal_symptoms",
            "medication_response",
            "hydration_status",
            "sleep_impact",
        ],
    },
    "chest_pain": {
        "display_name": "Chest Pain",
        "evidence": {
            "matching_cases": 4,
            "total_questions": 40,
            "strongest_groups": [
                "associated_respiratory",
                "cardiac_red_flags",
                "associated_systemic",
                "trigger_pattern",
                "duration_onset",
            ],
        },
        "required_fields": [
            "duration",
            "pain_character",
            "shortness_of_breath",
            "radiation",
            "palpitations",
            "dizziness_lightheadedness",
            "trigger_exertion_or_deep_breath",
            "fever_cough",
            "prior_episode_or_cardiac_history",
            "recent_medication_changes",
        ],
        "priority_order": [
            "shortness_of_breath",
            "radiation",
            "dizziness_lightheadedness",
            "palpitations",
            "pain_character",
            "duration",
            "trigger_exertion_or_deep_breath",
            "fever_cough",
            "prior_episode_or_cardiac_history",
            "recent_medication_changes",
        ],
        "conditional_priority": [
            {
                "when": {"chief_complaint": "chest_pain"},
                "promote": [
                    "shortness_of_breath",
                    "radiation",
                    "dizziness_lightheadedness",
                    "palpitations",
                ],
                "triage_hint": "Chest pain is safety-priority by default.",
            },
        ],
        "red_flags": [
            "shortness_of_breath",
            "radiation_arm_jaw_back",
            "palpitations",
            "dizziness",
            "fainting",
            "sweating",
            "exertional_chest_pain",
            "severe_pressure",
        ],
        "field_questions": {
            "shortness_of_breath": "Are you short of breath, or does it hurt to take a deep breath?",
            "radiation": "Does the pain spread to your arm, jaw, back, shoulder, or upper abdomen?",
            "dizziness_lightheadedness": "Are you feeling dizzy, lightheaded, or like you might faint?",
            "palpitations": "Are you having palpitations or an abnormal heartbeat?",
            "pain_character": "Does the chest discomfort feel like pressure, tightness, squeezing, burning, or sharp pain?",
            "duration": "When did the chest pain start, and how long has it been going on?",
            "trigger_exertion_or_deep_breath": "Does it get worse with walking, exertion, deep breathing, position, or stress?",
            "fever_cough": "Do you also have fever, chills, cough, or sore throat?",
            "prior_episode_or_cardiac_history": "Have you had this before, or do you have any heart history?",
            "recent_medication_changes": "Have you missed doses or had recent changes to your medications?",
        },
        "nlice_fields_to_keep": [
            "nature",
            "location",
            "intensity",
            "chronology",
            "excitation",
        ],
        "structured_fields": [
            "pressure_or_tightness",
            "shortness_of_breath",
            "radiation_arm_jaw_back",
            "palpitations",
            "dizziness",
            "exertional_trigger",
            "deep_breath_effect",
            "cardiac_history",
            "recent_medication_changes",
        ],
    },
    "abdominal_pain": {
        "display_name": "Abdominal Pain",
        "evidence": {
            "matching_cases": 56,
            "total_questions": 517,
            "strongest_groups": [
                "associated_gi",
                "associated_systemic",
                "duration_onset",
                "trigger_pattern",
                "medication_response",
                "cardiac_red_flags",
                "exposure_infection",
                "pregnancy_gyne",
                "hydration_urination",
            ],
        },
        "required_fields": [
            "duration",
            "pain_location",
            "pain_severity",
            "vomiting",
            "diarrhea_constipation",
            "stool_blood_or_dark",
            "fever_chills_body_aches",
            "hydration_urination",
            "food_diet_trigger",
            "medication_supplement_change",
            "pregnancy_menstrual_context",
            "travel_sick_contacts",
            "chest_breathing_back_red_flags",
            "lightheadedness_or_fall",
        ],
        "priority_order": [
            "pain_location",
            "duration",
            "vomiting",
            "diarrhea_constipation",
            "stool_blood_or_dark",
            "hydration_urination",
            "fever_chills_body_aches",
            "pain_severity",
            "pregnancy_menstrual_context",
            "lightheadedness_or_fall",
            "chest_breathing_back_red_flags",
            "food_diet_trigger",
            "medication_supplement_change",
            "travel_sick_contacts",
        ],
        "conditional_priority": [
            {
                "when": {"blood_in_stool": True},
                "promote": [
                    "danger_red_flags",
                    "hydration_urination",
                ],
            },
            {
                "when": {"pregnancy_possible": True},
                "promote": [
                    "pregnancy_menstrual_context",
                    "danger_red_flags",
                ],
            },
            {
                "when": {"vomiting_or_diarrhea": True},
                "promote": [
                    "hydration_urination",
                ],
            },
        ],
        "red_flags": [
            "blood_in_stool",
            "black_stool",
            "persistent_vomiting",
            "dehydration",
            "pregnancy_possible",
            "severe_pain",
            "lightheadedness",
            "fall",
            "chest_pain",
            "shortness_of_breath",
            "back_pain",
            "weight_loss",
        ],
        "field_questions": {
            "pain_location": "Where in your abdomen do you feel the pain most?",
            "duration": "How long have you had the abdominal pain?",
            "pain_severity": "On a scale from 0 to 10, how bad is the abdominal pain at its worst?",
            "vomiting": "Have you vomited?",
            "diarrhea_constipation": "Have you had diarrhea, constipation, or a change in bowel habits?",
            "stool_blood_or_dark": "Have you noticed blood in your stool or black, tarry stool?",
            "fever_chills_body_aches": "Do you have fever, chills, or body aches with the abdominal pain?",
            "hydration_urination": "Are you able to keep fluids down and urinate normally?",
            "food_diet_trigger": "Does the pain change after eating, or have you started a new diet?",
            "medication_supplement_change": "Have you started any new medicines or supplements recently?",
            "pregnancy_menstrual_context": "Is pregnancy possible, or have you had any menstrual changes?",
            "travel_sick_contacts": "Have you traveled recently or been around anyone with stomach illness?",
            "chest_breathing_back_red_flags": "Are you having chest pain, trouble breathing, or pain going to your back?",
            "lightheadedness_or_fall": "Do you feel lightheaded, or have you fallen?",
            "danger_red_flags": "Are you having severe pain, persistent vomiting, blood or black stool, fainting, dehydration, pregnancy concern, chest pain, trouble breathing, or back pain?",
        },
        "nlice_fields_to_keep": [
            "nature",
            "location",
            "intensity",
            "chronology",
            "excitation",
        ],
        "structured_fields": [
            "abdominal_location",
            "pain_severity",
            "vomiting",
            "diarrhea",
            "constipation",
            "blood_in_stool",
            "dark_stool",
            "fever",
            "hydration_status",
            "urination_normal",
            "food_trigger",
            "diet_change",
            "medication_or_supplement_change",
            "pregnancy_possible",
            "last_menstrual_period",
            "travel_or_sick_contacts",
            "lightheadedness",
            "fall",
            "back_pain",
        ],
    },
}


WORKFLOW_ALIASES = {
    "fever": "fever",
    "temperature": "fever",
    "high fever": "fever",
    "cough": "cough",
    "headache": "headache",
    "head pain": "headache",
    "migraine": "headache",
    "chest pain": "chest_pain",
    "chest tightness": "chest_pain",
    "chest pressure": "chest_pain",
    "abdominal pain": "abdominal_pain",
    "abdomen pain": "abdominal_pain",
    "stomach pain": "abdominal_pain",
    "belly pain": "abdominal_pain",
}


def workflow_key_for_complaint(chief_complaint: str) -> str:
    """Return the configured workflow key for complaint text."""

    normalized = (chief_complaint or "").strip().lower()
    for phrase, key in WORKFLOW_ALIASES.items():
        if phrase in normalized:
            return key
    return normalized.replace(" ", "_")


def get_workflow(chief_complaint: str) -> dict:
    """Return the configured workflow dictionary for complaint text."""

    return CLINICAL_WORKFLOWS.get(workflow_key_for_complaint(chief_complaint), {})
